# Site settings
title: Oracle Cloud Security and Management blog
email: 
description: "Oracle Cloud Security and Management."
baseurl: ""
url: "http://sttoracle.github.io"
github_username:  sttoracle

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
