# Site settings
title: Oracle Cloud Security and Management blog
email: 
description: "Oracle Cloud Security and Management."
baseurl: ""
url: "http://sttoracle.github.io"
twitter_username: karpathy
github_username:  karpathy

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
